name: "Continuous Integration: Terraform Docs"

on:
  pull_request:

jobs:
  docs:
    name: Generate Terraform documentation
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - id: clone_repository
        name: Clone repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - id: run_terraform_docs
        name: Render terraform docs and push changes back to PR
        # terraform-docs/gh-actions@1.0.0
        uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # v1.4.1
        with:
          working-dir: .
          output-file: README.md
          config-file: terraform-docs.yml
          output-method: inject
          git-push: "true"
          git-commit-message: "terraform-docs: updated markdown table"
